---
title: "Averge of predicted scores from 20 models"
author: "Si Liu"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
    code_folding: hide
    df_print: paged
params:
  timepoint: baseline
---
  
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png", dev.args = list(type = "cairo-png"), dpi=300)
options(bitmapType='cairo') # for generating png on linux
```

# Setup

## Loading libraries. 

```{r load_libraries, warning = FALSE, message = FALSE}
library(ggplot2)
theme_set(theme_classic())
library(ggpubr)
library(ggpointdensity)
library(viridis)
library(pROC)

```

```{r}

n_model = 20

data_list = c("HLA_I_all_match", "HLA_II_all_match", "HLA_I_full_mcpas", 
              "HLA_I_leave1out_match_B0702", "HLA_I_leave1out_match_B0801", 
              "HLA_I_leave1out_match_C0701")
```

# Take average of scores

```{r}

df_seeds = read.table("ensemble_seeds.txt", sep = "\t", header=FALSE)
dim(df_seeds)
head(df_seeds)

for (cur_data in data_list){
  
  print(cur_data)
  
  score_dir = paste0("results/predicted_scores/", cur_data, "_ensemble/")


  test_pos_list = c()
  test_neg_list = c()

  for (i in 1:n_model){
    
    seed_1 = as.character(df_seeds$V1[i])
    seed_2 = as.character(df_seeds$V2[i])
    seed_3 = as.character(df_seeds$V3[i])
    
    seeds_string = paste0("_", seed_1, "_", seed_2, "_", seed_3)
    
    df_test_pos = read.csv(paste0(score_dir, cur_data, "_pos_test", seeds_string, 
                                   "/predicted_scores.csv"), 
                            header=TRUE)    
    df_test_neg = read.csv(paste0(score_dir, cur_data, "_neg_test", seeds_string, 
                                   "/predicted_scores.csv"), 
                            header=TRUE)   
    
    test_pos_list[[i]] = df_test_pos$score
    test_neg_list[[i]] = df_test_neg$score 
    
  }

  print(length(test_pos_list))
  print(length(test_neg_list))
  
  
  test_pos_mat = matrix(unlist(test_pos_list), ncol=n_model, byrow=FALSE)
  test_neg_mat = matrix(unlist(test_neg_list), ncol=n_model, byrow=FALSE)
  
  print(dim(test_pos_mat))
  print(dim(test_neg_mat))
  
  stopifnot(all(test_pos_mat[1:5, 11] == test_pos_list[[11]][1:5]))
  stopifnot(all(test_neg_mat[1:5, 20] == test_neg_list[[20]][1:5]))
  
  
  # Save Out Files of Averaged Scores
  
  ave_test_pos = rowSums(test_pos_mat[, 1:n_model])/n_model
  ave_test_neg = rowSums(test_neg_mat[, 1:n_model])/n_model
  
  df_ave_test_pos = data.frame(tcr = df_test_pos$tcr, 
                               hla_allele = df_test_pos$hla_allele, 
                               ave = ave_test_pos)
  
  df_ave_test_neg = data.frame(tcr = df_test_neg$tcr, 
                               hla_allele = df_test_neg$hla_allele, 
                               ave = ave_test_neg)
  
  write.csv(df_ave_test_pos, 
            paste0("results/ensemble_scores/", cur_data, "/", cur_data, "_test_pos_", as.character(n_model), ".csv"), 
            row.names=FALSE)
  write.csv(df_ave_test_neg, 
            paste0("results/ensemble_scores/", cur_data, "/", cur_data, "_test_neg_", as.character(n_model), ".csv"), 
            row.names=FALSE)
  
  # AUC
  
  test_labels = c(rep(1, nrow(df_ave_test_pos)), rep(0, nrow(df_ave_test_neg)))
  
  print(paste0(cur_data, " test AUC:"))
  print(auc(test_labels, c(df_ave_test_pos$ave, df_ave_test_neg$ave)))
  print("                                          ")
  print("------------------------------------------")


}

```
# Session information
```{r}
sessionInfo()
```

